### ISSUE TITLE
Include postgresql-libpq

### ISSUE THREAD

**Issue by phadej** [Bodigrim/clc-stackage#3]
It's *quite* important lib:
- https://packdeps.haskellers.com/reverse/postgresql-libpq
- https://packdeps.haskellers.com/reverse/postgresql-simple

and only requires `libpq-dev` package do be installed on Debian based systems.

EDIT: `hpqtypes` also needs just `libpq-dev`

**Comment by Bodigrim** [comment]
I'd like to keep impact assessment accessible for Windows users. Maybe we can enable it under `if !os(windows)` section?..

**Comment by phadej** [comment]
There are a lot of packages which is harder to get working on windows. `brotli` needs a lib, `magic` needs a lib, `proto-lens-protobuf-types` needs `protoc` in scope. (EDIT: `postgresql-libpq`  often just compiles when postgresql is installed, for which installers are available - that is how i test it locally). So the current state is far from easy to compile on windows. (incl #4).

**Comment by tbidne** [comment]
This is resolved by https://github.com/haskell/clc-stackage/pull/18 fyi. `postgresql-libpq` is included [except windows](https://github.com/haskell/clc-stackage/blob/master/excluded_pkgs.json#L325).
